export const constants = {
    MERCHANT_PAYMENTS_FETCH: 'MERCHANT_PAYMENTS_FETCH',
    MERCHANT_PAYMENTS_SUCCESS: 'MERCHANT_PAYMENTS_SUCCESS',
    MERCHANT_PAYMENTS_ERROR: 'MERCHANT_PAYMENTS_ERROR',
}