export const currencies = [
    { label: "Rscoin", value: 'rsc' },
    { label: "Bitcoin", value: 'btc' },
    { label: "Ethereum", value: "eth" },
    { label: "Bitcoin Cash", value: "bch" },
    { label: "Dash Coin", value: "dash" },
    { label: "Lite Coin", value: "ltc" },
    { label: "ZCash", value: "zcash" },
    { label: "Ripple", value: "xrp" },
    { label: "US Dollar", value: "usd" },
    { label: "Euro", value: "eur" },
    { label: "Malaysian Ringget", value: "myr" },
    { label: "Singapore Dollar", value: "sgd" },
];

export const explorer ={
    "bch": {
        "id": "bch",
        "name": "Bitcoin Cash",
        "symbol": "฿",
        "explorer_transaction": "https://bch.btc.com/tx/",
        "explorer_address": "https://bch.btc.com/address/",
        "type": "coin",
        "deposit_fee": "0.0",
        "min_deposit_amount": "0.0",
        "withdraw_fee": 0.00042,
        "min_withdraw_amount": "0.0",
        "withdraw_limit_24h": "10.0",
        "withdraw_limit_72h": "30.0",
        "base_factor": 100000000,
        "precision": 8,
        "icon_url": "https://raw.githubusercontent.com/HafeezRai/cryptocurrency-icons/master/128/color/bch.png",
        "balance": 0,
        "locked": 0,
        "address": null
    },
    "btc": {
        "id": "btc",
        "name": "Bitcoin",
        "symbol": "฿",
        "explorer_transaction": "https://blockchain.info/tx/",
        "explorer_address": "https://blockchain.info/address/",
        "type": "coin",
        "deposit_fee": "0.0",
        "min_deposit_amount": "0.0",
        "withdraw_fee": 0.00042,
        "min_withdraw_amount": "0.0",
        "withdraw_limit_24h": "2.0",
        "withdraw_limit_72h": "10.0",
        "base_factor": 100000000,
        "precision": 8,
        "icon_url": "https://raw.githubusercontent.com/HafeezRai/cryptocurrency-icons/master/128/color/btc.png",
        "balance": 0,
        "locked": 0,
        "address": null
    },
    "dash": {
        "id": "dash",
        "name": "Dashcoin",
        "symbol": "Đ",
        "explorer_transaction": "https://live.blockcypher.com/dash/tx/",
        "explorer_address": "https://live.blockcypher.com/dash/",
        "type": "coin",
        "deposit_fee": "0.0",
        "min_deposit_amount": "0.0",
        "withdraw_fee": 0.00042,
        "min_withdraw_amount": "0.0",
        "withdraw_limit_24h": "20.0",
        "withdraw_limit_72h": "100.0",
        "base_factor": 100000000,
        "precision": 8,
        "icon_url": "https://raw.githubusercontent.com/HafeezRai/cryptocurrency-icons/master/128/color/dash.png",
        "balance": 0,
        "locked": 0,
        "address": null
    },
    "eth": {
        "id": "eth",
        "name": "Ethereum",
        "symbol": "Ξ",
        "explorer_transaction": "https://etherscan.io/tx/",
        "explorer_address": "https://etherscan.io/address/",
        "type": "coin",
        "deposit_fee": "0.0",
        "min_deposit_amount": "0.00021",
        "withdraw_fee": 0.00042,
        "min_withdraw_amount": "0.0",
        "withdraw_limit_24h": "10.0",
        "withdraw_limit_72h": "30.0",
        "base_factor": 1000000000000000000,
        "precision": 8,
        "icon_url": "https://raw.githubusercontent.com/HafeezRai/cryptocurrency-icons/master/128/color/eth.png",
        "balance": 0,
        "locked": 0,
        "address": null
    },
    "eur": {
        "id": "eur",
        "name": "Euro",
        "symbol": "€",
        "type": "fiat",
        "deposit_fee": "5.0",
        "min_deposit_amount": "0.0",
        "withdraw_fee": 0,
        "min_withdraw_amount": "0.0",
        "withdraw_limit_24h": "0.0",
        "withdraw_limit_72h": "0.0",
        "base_factor": 1,
        "precision": 2,
        "icon_url": "https://raw.githubusercontent.com/atomiclabs/cryptocurrency-icons/master/128/icon/eur.png",
        "balance": 0,
        "locked": 0,
        "address": null
    },
    "ltc": {
        "id": "ltc",
        "name": "Litecoin",
        "symbol": "Ł",
        "explorer_transaction": "https://chain.so/tx/LTC/",
        "explorer_address": "https://chain.so/address/LTC/",
        "type": "coin",
        "deposit_fee": "0.0",
        "min_deposit_amount": "0.0",
        "withdraw_fee": 0.00042,
        "min_withdraw_amount": "0.00042",
        "withdraw_limit_24h": "100.0",
        "withdraw_limit_72h": "300.0",
        "base_factor": 100000000,
        "precision": 8,
        "icon_url": "https://raw.githubusercontent.com/HafeezRai/cryptocurrency-icons/master/128/color/ltc.png",
        "balance": 0,
        "locked": 0,
        "address": null
    },
    "myr": {
        "id": "myr",
        "name": "Malaysian Ringgit",
        "symbol": "R",
        "type": "fiat",
        "deposit_fee": "5.0",
        "min_deposit_amount": "0.0",
        "withdraw_fee": 0,
        "min_withdraw_amount": "0.0",
        "withdraw_limit_24h": "0.0",
        "withdraw_limit_72h": "0.0",
        "base_factor": 1,
        "precision": 2,
        "icon_url": "https://www.xe.com/themes/xe/images/flags/big/myr.png",
        "balance": 73.99,
        "locked": 16.01,
        "address": null
    },
    "sgd": {
        "id": "sgd",
        "name": "Singapore Dollar",
        "symbol": "$",
        "type": "fiat",
        "deposit_fee": "5.0",
        "min_deposit_amount": "0.0",
        "withdraw_fee": 0,
        "min_withdraw_amount": "0.0",
        "withdraw_limit_24h": "0.0",
        "withdraw_limit_72h": "0.0",
        "base_factor": 1,
        "precision": 2,
        "icon_url": "https://www.xe.com/themes/xe/images/flags/big/sgd.png",
        "balance": 0,
        "locked": 0,
        "address": null
    },
    "usd": {
        "id": "usd",
        "name": "US Dollar",
        "symbol": "$",
        "type": "fiat",
        "deposit_fee": "5.0",
        "min_deposit_amount": "0.0",
        "withdraw_fee": 0,
        "min_withdraw_amount": "0.0",
        "withdraw_limit_24h": "100.0",
        "withdraw_limit_72h": "200.0",
        "base_factor": 1,
        "precision": 2,
        "icon_url": "https://raw.githubusercontent.com/atomiclabs/cryptocurrency-icons/master/128/icon/usd.png",
        "balance": 84.05,
        "locked": 3.95,
        "address": null
    }
}


