export const constants = {
    MERCHANT_WEBSITE_FETCH: 'MERCHANT_WEBSITE_FETCH',
    MERCHANT_WEBSITE_SUCCESS: 'MERCHANT_WEBSITE_SUCCESS',
    MERCHANT_WEBSITE_ERROR: 'MERCHANT_WEBSITE_ERROR',

    MERCHANT_WEBSITE_UPDATE: "MERCHANT_WEBSITE_UPDATE",
    MERCHANT_WEBSITE_UPDATE_SUCCESS: "MERCHANT_WEBSITE_UPDATE_SUCCESS",
    MERCHANT_WEBSITE_UPDATE_ERROR: "MERCHANT_WEBSITE_UPDATE_ERROR",
}